### ISSUE TITLE
Race condition in consumable shard detection

### ISSUE THREAD

**Issue by wegenmic** [wem/vertx-kinesis-consumer-orchestra#23]
The following can be reproduced with version 0.8.0
VKCO is configured to consume 1 shard per Vert.x instance.

Having a Kinesis stream with multiple shards, it might happen that `NotConsumedShardDetectorVerticle` from different Vert.x instances try to grab the same shard to process. In the end only one instance gets to consume said shard, which is perfectly fine.
The problem is with the other Vert.x instance(s) that didn't get to consume the shard. It seems somewhere in the loop between `NotConsumedShardDetectorVerticle` and `ConsumerControlVerticle` is an issue that prevents the "losing" instance getting back in the mode to detect shards with no consumer. This results in a Kinesis stream with shards that are not consumed. This instance is now in a state where only a restart of the instance will resolve the issue.

After a log entry from `NotConsumedShardDetectorVerticle`
```
logger.info {
        "Not consumed shards detected ${availableShards.joinToString { it.shardId() }}. " +
                "Will send start command for shards ${shardIdListToConsume.joinToString()} according to " +
                "\"parent(s) must be finished first\" rule."
        }
```

There follows a log entry from `ConsumerControlVerticle`
```
logger.info { "Currently no shards get consumed on stream \"${options.clusterName.streamName}\"." }
```

After that the Vert.x instance shows no more log statements.

What might help is a test that will cover this race condition together with a fix for the problem. Additional logging in this area could help as well with troubleshooting further issues.

**Comment by wem** [comment]
fixed in 0.8.1: https://jcenter.bintray.com/ch/sourcemotion/vertx/vertx-kinesis-consumer-orchestra/0.8.1/
